
import 'bootstrap-icons/font/bootstrap-icons.css'
import "boxicons/css/boxicons.css";
import "bootstrap/dist/css/bootstrap.css"
import "glightbox/dist/css/glightbox.css"

import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import Hedder from './components/Hedder';


const raleway = Raleway ({subsets: ['latin']});

export const metadata: Metadata = {
  title: "Personal Profile Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Hedder />
        {children}</body>
    </html>
  );
}
